add_subdirectory(core)
add_subdirectory(core_ui)
add_subdirectory(libui)
add_subdirectory(api)
add_subdirectory(topology)
add_subdirectory(protocol)
add_subdirectory(icd_utility)
add_subdirectory(engine)
add_subdirectory(visualizer)
add_subdirectory(runconfig)
add_subdirectory(test_program)
add_subdirectory(app)
add_subdirectory(plugins)